### ISSUE TITLE
Thanks very much! Excellent project, clear instructions, worked for me first time

### ISSUE THREAD

**Issue by rrthomas** [Codeuctivity/UnlockLuksOnBootByToken#3]
Sorry for filing this as an issue, but I wanted to thank the author of this project, and couldn't find another way to do it.

This project solved exactly the problem I had: wanting to boot my cryptsetup machine without entering the passphrase or decrypting the disk. The instructions were clear and worked for me first time.

Thanks again!

**Comment by stesee** [comment]
I'm glad that it is of use
